{% set version = "0.25.0" %}

package:
  name: fbpic
  version: {{ version }}

source:
  url: https://github.com/fbpic/fbpic/archive/refs/tags/{{ version }}.tar.gz
  sha256: a868cae099fac66d20017d405caea17cb3f1aa00cb83489038f4474ca8fd28f3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - h5py
    - numba
    - numpy
    - python >=3.6
    - python-dateutil
    - scipy
# For fast non-MKL FFTs, explore using in the future:
# https://github.com/fbpic/fbpic#installation
# pyfftw

test:
  imports:
    - fbpic

about:
  home: https://fbpic.github.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: Fourier-Bessel Particle-In-Cell code (FBPIC)

  description: |
    FBPIC is a Particle-In-Cell (PIC) code for relativistic plasma physics.
    It is especially well-suited for physical simulations of laser-wakefield
    acceleration and plasma-wakefield acceleration, with close-to-cylindrical
    symmetry.
  dev_url: https://github.com/fbpic/fbpic

extra:
  recipe-maintainers:
    - ax3l
    - MKirchen
    - RemiLehe
    - soerenjalas
